name: Copy File Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Creation of folder1 and multiple files
        run: |
          mkdir folder1
          echo "Hello World from File 1" > folder1/file1.txt
          echo "Hello World from File 2" > folder1/file2.txt
          echo "Hello World from File 3" > folder1/file3.txt

      # Runs a set of commands using the runners shell
      - name: creation of foddler2
        run: mkdir folder2
      
      - name: move all files to folder2
        run: mv folder1/file2.txt folder1/file3.txt folder2/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: file3_txt
          path: folder2/file3.txt
          retention-days: 7
